# Generated by Django 2.0.4 on 2018-07-17 11:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='title2',
            field=models.TextField(max_length=200),
        ),
    ]
