# Generated by Django 2.0.4 on 2018-07-18 06:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_auto_20180717_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
