# Generated by Django 2.0.4 on 2018-07-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelforms', '0002_auto_20180717_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_title',
            field=models.CharField(max_length=100),
        ),
    ]
